apiVersion: apps/v1
kind: Deployment
metadata:
  name: peisistratos-dev
  namespace: odysseia
  labels:
    env: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peisistratos-dev
  template:
    metadata:
      labels:
        app: peisistratos-dev
    spec:
      serviceAccountName: solon-access-sa
      containers:
        - name: peisistratos
          image: ghcr.io/odysseia-greek/peisistratos
          imagePullPolicy: Never
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AUTH_METHOD
              value: token
          envFrom:
            - configMapRef:
                name: solon
          volumeMounts:
            - name: vault-server-tls
              mountPath: /etc/certs/vault
              readOnly: true
          ports:
            - containerPort: 2345
              name: delve
      volumes:
        - name: vault-server-tls
          secret:
            secretName: vault-server-tls
---
apiVersion: v1
kind: Service
metadata:
  name: peisistratos-dev
spec:
  ports:
    - port: 2345
      name: delve
      targetPort: delve
  selector:
    app: peisistratos-dev
