apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: odysseia
deploy:
  kubeContext: k3d-odysseia
  tolerateFailuresUntilDeadline: true
build:
  local:
    push: false

profiles:
  - name: ptolemaios
    build:
      artifacts:
        - image: ghcr.io/odysseia-greek/ptolemaios
          context: ptolemaios
          docker:
            target: debug
          sync:
            manual:
              - src: '**/*.go'
                dest: '/app'
    manifests:
      rawYaml:
        - ptolemaios/infra/manifest.yaml