// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/ptolemaios.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PtolemaiosClient is the client API for Ptolemaios service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PtolemaiosClient interface {
	// Get the config from ptolemaios
	GetSecret(ctx context.Context, in *VaultRequest, opts ...grpc.CallOption) (*ElasticConfigVault, error)
	GetNamedSecret(ctx context.Context, in *VaultRequestNamed, opts ...grpc.CallOption) (*ElasticConfigVault, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	ShutDown(ctx context.Context, in *ShutDownRequest, opts ...grpc.CallOption) (*ShutDownResponse, error)
}

type ptolemaiosClient struct {
	cc grpc.ClientConnInterface
}

func NewPtolemaiosClient(cc grpc.ClientConnInterface) PtolemaiosClient {
	return &ptolemaiosClient{cc}
}

func (c *ptolemaiosClient) GetSecret(ctx context.Context, in *VaultRequest, opts ...grpc.CallOption) (*ElasticConfigVault, error) {
	out := new(ElasticConfigVault)
	err := c.cc.Invoke(ctx, "/delphi_ptolemaios.Ptolemaios/GetSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ptolemaiosClient) GetNamedSecret(ctx context.Context, in *VaultRequestNamed, opts ...grpc.CallOption) (*ElasticConfigVault, error) {
	out := new(ElasticConfigVault)
	err := c.cc.Invoke(ctx, "/delphi_ptolemaios.Ptolemaios/GetNamedSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ptolemaiosClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/delphi_ptolemaios.Ptolemaios/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ptolemaiosClient) ShutDown(ctx context.Context, in *ShutDownRequest, opts ...grpc.CallOption) (*ShutDownResponse, error) {
	out := new(ShutDownResponse)
	err := c.cc.Invoke(ctx, "/delphi_ptolemaios.Ptolemaios/ShutDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PtolemaiosServer is the server API for Ptolemaios service.
// All implementations must embed UnimplementedPtolemaiosServer
// for forward compatibility
type PtolemaiosServer interface {
	// Get the config from ptolemaios
	GetSecret(context.Context, *VaultRequest) (*ElasticConfigVault, error)
	GetNamedSecret(context.Context, *VaultRequestNamed) (*ElasticConfigVault, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	ShutDown(context.Context, *ShutDownRequest) (*ShutDownResponse, error)
	mustEmbedUnimplementedPtolemaiosServer()
}

// UnimplementedPtolemaiosServer must be embedded to have forward compatible implementations.
type UnimplementedPtolemaiosServer struct {
}

func (UnimplementedPtolemaiosServer) GetSecret(context.Context, *VaultRequest) (*ElasticConfigVault, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedPtolemaiosServer) GetNamedSecret(context.Context, *VaultRequestNamed) (*ElasticConfigVault, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamedSecret not implemented")
}
func (UnimplementedPtolemaiosServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPtolemaiosServer) ShutDown(context.Context, *ShutDownRequest) (*ShutDownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutDown not implemented")
}
func (UnimplementedPtolemaiosServer) mustEmbedUnimplementedPtolemaiosServer() {}

// UnsafePtolemaiosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PtolemaiosServer will
// result in compilation errors.
type UnsafePtolemaiosServer interface {
	mustEmbedUnimplementedPtolemaiosServer()
}

func RegisterPtolemaiosServer(s grpc.ServiceRegistrar, srv PtolemaiosServer) {
	s.RegisterService(&Ptolemaios_ServiceDesc, srv)
}

func _Ptolemaios_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtolemaiosServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delphi_ptolemaios.Ptolemaios/GetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtolemaiosServer).GetSecret(ctx, req.(*VaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ptolemaios_GetNamedSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultRequestNamed)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtolemaiosServer).GetNamedSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delphi_ptolemaios.Ptolemaios/GetNamedSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtolemaiosServer).GetNamedSecret(ctx, req.(*VaultRequestNamed))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ptolemaios_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtolemaiosServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delphi_ptolemaios.Ptolemaios/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtolemaiosServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ptolemaios_ShutDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtolemaiosServer).ShutDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delphi_ptolemaios.Ptolemaios/ShutDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtolemaiosServer).ShutDown(ctx, req.(*ShutDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ptolemaios_ServiceDesc is the grpc.ServiceDesc for Ptolemaios service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ptolemaios_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delphi_ptolemaios.Ptolemaios",
	HandlerType: (*PtolemaiosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _Ptolemaios_GetSecret_Handler,
		},
		{
			MethodName: "GetNamedSecret",
			Handler:    _Ptolemaios_GetNamedSecret_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Ptolemaios_Health_Handler,
		},
		{
			MethodName: "ShutDown",
			Handler:    _Ptolemaios_ShutDown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ptolemaios.proto",
}
