root = "/app"

[build]
cmd = 'go build -gcflags "all=-N -l" github.com/odysseia-greek/delphi/solon .'
bin = "/app/solon"
full_bin = "dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec /app/solon"
watch = ["./..."]
include_ext = ["go", "tpl", "tmpl", "html"]
