// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: proto/aristides.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VaultRequest) Reset() {
	*x = VaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_aristides_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultRequest) ProtoMessage() {}

func (x *VaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aristides_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultRequest.ProtoReflect.Descriptor instead.
func (*VaultRequest) Descriptor() ([]byte, []int) {
	return file_proto_aristides_proto_rawDescGZIP(), []int{0}
}

type VaultRequestNamed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodName string `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
}

func (x *VaultRequestNamed) Reset() {
	*x = VaultRequestNamed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_aristides_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultRequestNamed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultRequestNamed) ProtoMessage() {}

func (x *VaultRequestNamed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aristides_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultRequestNamed.ProtoReflect.Descriptor instead.
func (*VaultRequestNamed) Descriptor() ([]byte, []int) {
	return file_proto_aristides_proto_rawDescGZIP(), []int{1}
}

func (x *VaultRequestNamed) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_aristides_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aristides_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_aristides_proto_rawDescGZIP(), []int{2}
}

type ShutDownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ShutDownRequest) Reset() {
	*x = ShutDownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_aristides_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutDownRequest) ProtoMessage() {}

func (x *ShutDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aristides_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutDownRequest.ProtoReflect.Descriptor instead.
func (*ShutDownRequest) Descriptor() ([]byte, []int) {
	return file_proto_aristides_proto_rawDescGZIP(), []int{3}
}

func (x *ShutDownRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// The response message with the config taken from vault
type ElasticConfigVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElasticUsername string `protobuf:"bytes,1,opt,name=elasticUsername,proto3" json:"elasticUsername,omitempty"`
	ElasticPassword string `protobuf:"bytes,2,opt,name=elasticPassword,proto3" json:"elasticPassword,omitempty"`
	ElasticCERT     string `protobuf:"bytes,3,opt,name=ElasticCERT,proto3" json:"ElasticCERT,omitempty"`
}

func (x *ElasticConfigVault) Reset() {
	*x = ElasticConfigVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_aristides_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElasticConfigVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElasticConfigVault) ProtoMessage() {}

func (x *ElasticConfigVault) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aristides_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElasticConfigVault.ProtoReflect.Descriptor instead.
func (*ElasticConfigVault) Descriptor() ([]byte, []int) {
	return file_proto_aristides_proto_rawDescGZIP(), []int{4}
}

func (x *ElasticConfigVault) GetElasticUsername() string {
	if x != nil {
		return x.ElasticUsername
	}
	return ""
}

func (x *ElasticConfigVault) GetElasticPassword() string {
	if x != nil {
		return x.ElasticPassword
	}
	return ""
}

func (x *ElasticConfigVault) GetElasticCERT() string {
	if x != nil {
		return x.ElasticCERT
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Health bool `protobuf:"varint,1,opt,name=health,proto3" json:"health,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_aristides_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aristides_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_aristides_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealth() bool {
	if x != nil {
		return x.Health
	}
	return false
}

type ShutDownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShutDownResponse) Reset() {
	*x = ShutDownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_aristides_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutDownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutDownResponse) ProtoMessage() {}

func (x *ShutDownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aristides_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutDownResponse.ProtoReflect.Descriptor instead.
func (*ShutDownResponse) Descriptor() ([]byte, []int) {
	return file_proto_aristides_proto_rawDescGZIP(), []int{6}
}

var File_proto_aristides_proto protoreflect.FileDescriptor

var file_proto_aristides_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x64, 0x65, 0x6c, 0x70, 0x68, 0x69, 0x5f,
	0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x56, 0x61, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x11, 0x56, 0x61, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x53, 0x68,
	0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x8a, 0x01, 0x0a, 0x12, 0x45, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x6c, 0x61, 0x73,
	0x74, 0x69, 0x63, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x6c, 0x61,
	0x73, 0x74, 0x69, 0x63, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x45, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x43, 0x45, 0x52, 0x54, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x45, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x43, 0x45, 0x52, 0x54, 0x22, 0x28,
	0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x68, 0x75, 0x74,
	0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe3, 0x02, 0x0a,
	0x09, 0x41, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73, 0x12, 0x53, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1e, 0x2e, 0x64, 0x65, 0x6c, 0x70, 0x68, 0x69,
	0x5f, 0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x65, 0x6c, 0x70, 0x68, 0x69,
	0x5f, 0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x45, 0x6c, 0x61, 0x73, 0x74,
	0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12,
	0x5d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x12, 0x23, 0x2e, 0x64, 0x65, 0x6c, 0x70, 0x68, 0x69, 0x5f, 0x61, 0x72, 0x69, 0x73, 0x74,
	0x69, 0x64, 0x65, 0x73, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x64, 0x1a, 0x24, 0x2e, 0x64, 0x65, 0x6c, 0x70, 0x68, 0x69, 0x5f,
	0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x45, 0x6c, 0x61, 0x73, 0x74, 0x69,
	0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x4d,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1f, 0x2e, 0x64, 0x65, 0x6c, 0x70, 0x68,
	0x69, 0x5f, 0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x65, 0x6c, 0x70,
	0x68, 0x69, 0x5f, 0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a,
	0x08, 0x53, 0x68, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x21, 0x2e, 0x64, 0x65, 0x6c, 0x70,
	0x68, 0x69, 0x5f, 0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x75,
	0x74, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64,
	0x65, 0x6c, 0x70, 0x68, 0x69, 0x5f, 0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73, 0x2e,
	0x53, 0x68, 0x75, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x64, 0x79, 0x73, 0x73, 0x65, 0x69, 0x61, 0x2d, 0x67, 0x72, 0x65, 0x65, 0x6b, 0x2f,
	0x64, 0x65, 0x6c, 0x70, 0x68, 0x69, 0x2f, 0x61, 0x72, 0x69, 0x73, 0x74, 0x69, 0x64, 0x65, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_aristides_proto_rawDescOnce sync.Once
	file_proto_aristides_proto_rawDescData = file_proto_aristides_proto_rawDesc
)

func file_proto_aristides_proto_rawDescGZIP() []byte {
	file_proto_aristides_proto_rawDescOnce.Do(func() {
		file_proto_aristides_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_aristides_proto_rawDescData)
	})
	return file_proto_aristides_proto_rawDescData
}

var file_proto_aristides_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_aristides_proto_goTypes = []interface{}{
	(*VaultRequest)(nil),       // 0: delphi_aristides.VaultRequest
	(*VaultRequestNamed)(nil),  // 1: delphi_aristides.VaultRequestNamed
	(*HealthRequest)(nil),      // 2: delphi_aristides.HealthRequest
	(*ShutDownRequest)(nil),    // 3: delphi_aristides.ShutDownRequest
	(*ElasticConfigVault)(nil), // 4: delphi_aristides.ElasticConfigVault
	(*HealthResponse)(nil),     // 5: delphi_aristides.HealthResponse
	(*ShutDownResponse)(nil),   // 6: delphi_aristides.ShutDownResponse
}
var file_proto_aristides_proto_depIdxs = []int32{
	0, // 0: delphi_aristides.Aristides.GetSecret:input_type -> delphi_aristides.VaultRequest
	1, // 1: delphi_aristides.Aristides.GetNamedSecret:input_type -> delphi_aristides.VaultRequestNamed
	2, // 2: delphi_aristides.Aristides.Health:input_type -> delphi_aristides.HealthRequest
	3, // 3: delphi_aristides.Aristides.ShutDown:input_type -> delphi_aristides.ShutDownRequest
	4, // 4: delphi_aristides.Aristides.GetSecret:output_type -> delphi_aristides.ElasticConfigVault
	4, // 5: delphi_aristides.Aristides.GetNamedSecret:output_type -> delphi_aristides.ElasticConfigVault
	5, // 6: delphi_aristides.Aristides.Health:output_type -> delphi_aristides.HealthResponse
	6, // 7: delphi_aristides.Aristides.ShutDown:output_type -> delphi_aristides.ShutDownResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_aristides_proto_init() }
func file_proto_aristides_proto_init() {
	if File_proto_aristides_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_aristides_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_aristides_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultRequestNamed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_aristides_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_aristides_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutDownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_aristides_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElasticConfigVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_aristides_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_aristides_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutDownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_aristides_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_aristides_proto_goTypes,
		DependencyIndexes: file_proto_aristides_proto_depIdxs,
		MessageInfos:      file_proto_aristides_proto_msgTypes,
	}.Build()
	File_proto_aristides_proto = out.File
	file_proto_aristides_proto_rawDesc = nil
	file_proto_aristides_proto_goTypes = nil
	file_proto_aristides_proto_depIdxs = nil
}
